package hg.engine;

import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.files.FileHandle;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.BitmapFont;

import java.util.HashMap;

/**
 * Offers basic load / unload functionality. Not thread-safe.
 * Loading is supported for textures, and sound files.
 * Music files should be used directly with the Audio Engine by specifying the path.
 */
public class AssetLoader {
    // Libraries
    private final HashMap<String, Texture> textureLibrary = new HashMap<>();
    private final HashMap<String, Sound> soundLibrary = new HashMap<>();
    private final HashMap<String, BitmapFont> fontLibrary = new HashMap<>();

    public AssetLoader() {}

    /** Loads a texture from disk. Repeated calls for the same path will return the same object.
     * @param sPath Path to the texture.
     * @return The loaded texture, or null if load failed. */
    public Texture loadTexture(String sPath) {
        if (textureLibrary.containsKey(sPath)) {
            return textureLibrary.get(sPath);
        }
        try {
            Texture xTex = new Texture(new FileHandle(sPath));
            xTex.setFilter(Texture.TextureFilter.Linear, Texture.TextureFilter.Linear);
            textureLibrary.put(sPath, xTex);
            return xTex;
        } catch (Exception e) {
            System.out.println("Couldn't load image at " + sPath);
            return null;
        }
    }

    /** Unloads a texture. Does nothing if the texture isn't loaded.
     * @param sPath The texture's path, which was used previously in a loadTexture() call. */
    public void unloadTexture(String sPath) {
        Texture target = textureLibrary.remove(sPath);
        if (target != null) {
            target.dispose();
        }
    }

    /** Loads a sound from disk. Repeated calls for the same path will return the same object.
     * @param sPath Path to the sound.
     * @return The loaded sound, or null if load failed. */
    public Sound loadSound(String sPath) {
        if (soundLibrary.containsKey(sPath)) {
            return soundLibrary.get(sPath);
        }
        try {
            Sound xSound = Gdx.audio.newSound(new FileHandle(sPath));
            soundLibrary.put(sPath, xSound);
            return xSound;
        } catch (Exception e) {
            System.out.println("Couldn't load sound at " + sPath);
            return null;
        }
    }

    /** Unloads a sound. Does nothing if the sound isn't loaded.
     * @param sPath The sound's path, which was used previously in a loadSound() call. */
    public void unloadSound(String sPath) {
        Sound target = soundLibrary.remove(sPath);
        if (target != null) {
            target.dispose();
        }
    }

    /** Loads a font from disk. Repeated calls for the same path will return the same object.
     * Fonts are a texture / data pair generated by https://www.angelcode.com/products/bmfont/
     * You must supply the path to the data file as "MyFont.fnt". More files may be queried depending
     * on the content of the font description.
     * @param sPath Path to the font's data (".fnt")
     * @return The loaded font, or null if load failed. */
    public BitmapFont loadFont(String sPath) {
        if (fontLibrary.containsKey(sPath)) {
            return fontLibrary.get(sPath);
        }
        try {
            BitmapFont xSound = new BitmapFont(new FileHandle(sPath));
            fontLibrary.put(sPath, xSound);
            return xSound;
        } catch (Exception e) {
            System.out.println("Couldn't load font at " + sPath);
            return null;
        }
    }

    /** Unloads a sound. Does nothing if the sound isn't loaded.
     * @param sPath The sound's path, which was used previously in a loadSound() call. */
    public void unloadFont(String sPath) {
        BitmapFont target = fontLibrary.remove(sPath);
        if (target != null) {
            target.dispose();
        }
    }

    /** Unloads everything previously loaded. */
    public void unloadAll() {
        // Textures
        for (var texture : textureLibrary.entrySet()) {
            texture.getValue().dispose();
        }
        textureLibrary.clear();
        // Sounds
        for (var sound : soundLibrary.entrySet()) {
            sound.getValue().dispose();
        }
        soundLibrary.clear();
    }
}
